# Generated by Django 4.2.5 on 2023-11-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_uploadedfile_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_hash',
            field=models.CharField(default='', max_length=64),
        ),
    ]
